name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy and Run SSH Commands on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Connected to EC2 (Ubuntu)!"
    
          # Update packages
          sudo apt-get update -y
          sudo apt-get install -y curl
    
          # Install Node.js if not installed
          if ! command -v node > /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
    
          # Install pnpm if not installed
          if ! command -v pnpm > /dev/null; then
            npm install -g pnpm
          fi
    
          # Install pm2 if not installed
          if ! command -v pm2 > /dev/null; then
            npm install -g pm2
          fi
    
          # Move to project directory
          cd /home/ec2-user/CI-Next-App/
    
          # Pull latest code
          git pull
    
          # Install project dependencies
          pnpm install
    
          # Build the project
          pnpm run build
    
          # Restart servers using pm2
          pm2 restart fe-server || pm2 start npm --name fe-server -- run start
          pm2 restart http-server || pm2 start npm --name http-server -- run start
          pm2 restart ws-server || pm2 start npm --name ws-server -- run start
    
          # Save pm2 processes
          pm2 save           