name: CD Staging Workflow

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying Everything to Staging Cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH Into Server
        run: echo "hi"
          