name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected to EC2!"

            cd /home/ubuntu/CI-Next-App/
            git pull

            pnpm install
            pnpm run build

            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server